### ISSUE TITLE
Send finishing time with text message 

### ISSUE THREAD

**Issue by billwright** [SplitTime/OpenSplitTime#107]
Runners will want to know this. Also, if possible, send overall placement in gender. Because of the wave start overall placement is only meaningful if those placements are based on time in the race and not on the time-of-day finishing time.

**Comment by moveson** [comment]
PR #110 addresses the elapsed time issue. It would not be possible to provide reliable overall placement or gender placement because start times may differ, and therefore a runner's overall placement or gender placement may change as later starters come in with potentially faster times.
