### ISSUE TITLE
When using RunSignup v2 API Keys, "Manage and Sync" is a dead end

### ISSUE THREAD

**Issue by yanatan16** [SplitTime/OpenSplitTime#1158]
When I configured the API Keys for RunSignup with their v2 keys instead of the legacy ones, the Manage and Sync page showed no box that said "Preview Sync", instead it felt like a dead end. Example below:

<img width="1176" alt="Screenshot 2023-09-22 at 8 54 44 AM" src="https://github.com/SplitTime/OpenSplitTime/assets/938655/96fa85e3-2524-4a61-96ab-6c33ff27be1d">

**Comment by moveson** [comment]
I'm able to reproduce this problem anytime a Race ID does not return any Events. I believe the solution is to check for presence of Events and display an error message if none are returned.
