### ISSUE TITLE
Bib in the Wrong Event Errors

### ISSUE THREAD

**Issue by legoabram** [SplitTime/OpenSplitTime#161]
Server does not like it when there are time rows with a bib number and a split that don't belong together.

### split_raw_time_rows

ArgumentError at /api/v1/event_groups/92/submit_raw_time_rows
=============================================================

> arguments must include split_id

app/services/args_validator.rb, line 69
---------------------------------------

``` ruby
   64   
   65     def validate_required_params
   66       required.each do |required_arg|
   67         if params[required_arg].nil?
   68           notify_console(args)
>  69           raise ArgumentError, "arguments #{for_klass}must include #{required_arg}"
   70         end
   71       end
   72     end
   73   
   74     def validate_required_alternatives
```

App backtrace
-------------

 - app/services/args_validator.rb:69:in `block in validate_required_params'
 - app/services/args_validator.rb:66:in `each'
 - app/services/args_validator.rb:66:in `validate_required_params'
 - app/services/args_validator.rb:35:in `validate'
 - app/services/args_validator.rb:8:in `validate'
 - app/services/find_expected_lap.rb:9:in `initialize'
 - app/services/find_expected_lap.rb:5:in `new'
 - app/services/find_expected_lap.rb:5:in `perform'
 - app/services/enrich_raw_time_row.rb:53:in `expected_lap'
 - app/services/enrich_raw_time_row.rb:45:in `block in add_lap_to_raw_times'
 - app/services/enrich_raw_time_row.rb:37:in `each'
 - app/services/enrich_raw_time_row.rb:37:in `add_lap_to_raw_times'
 - app/services/enrich_raw_time_row.rb:25:in `perform'
 - app/services/enrich_raw_time_row.rb:10:in `perform'
 - app/services/interactors/submit_raw_time_rows.rb:60:in `enrich_raw_time_row'
 - app/services/interactors/submit_raw_time_rows.rb:31:in `block (2 levels) in perform!'
 - app/services/interactors/submit_raw_time_rows.rb:29:in `block in perform!'
 - app/services/interactors/submit_raw_time_rows.rb:28:in `each'
 - app/services/interactors/submit_raw_time_rows.rb:28:in `perform!'
 - app/services/interactors/submit_raw_time_rows.rb:8:in `perform!'
 - app/controllers/api/v1/event_groups_controller.rb:138:in `submit_raw_time_rows'
 - config/initializers/wrap_parameters.rb:17:in `process_action'

### Using the "Pull Times" Button

ArgumentError at /api/v1/event_groups/92/pull_raw_times
=======================================================

> time_point is not contained in the provided lap_splits

app/services/split_time_finder.rb, line 72
------------------------------------------

``` ruby
   67     def scoped_split_times
   68       valid ? split_times.select { |st| st.time_from_start && st.valid_status? } : split_times
   69     end
   70   
   71     def validate_setup
>  72       raise ArgumentError, 'time_point is not contained in the provided lap_splits' unless
   73           ordered_time_points.include?(time_point)
   74       raise ArgumentError, 'split_times do not all belong to the same effort' unless
   75           split_times.map(&:effort_id).uniq.size < 2
   76       raise ArgumentError, 'split_times do not relate to the provided effort' if
   77           effort && split_times.any? { |st| st.effort_id != effort.id }
```

App backtrace
-------------

 - app/services/split_time_finder.rb:72:in `validate_setup'
 - app/services/split_time_finder.rb:28:in `initialize'
 - app/services/split_time_finder.rb:6:in `new'
 - app/services/split_time_finder.rb:6:in `prior'
 - app/services/find_expected_lap.rb:41:in `previous_value'
 - app/services/find_expected_lap.rb:35:in `time_fits_missing'
 - app/services/find_expected_lap.rb:30:in `block in missing_lap'
 - app/services/find_expected_lap.rb:30:in `find'
 - app/services/find_expected_lap.rb:30:in `missing_lap'
 - app/services/find_expected_lap.rb:21:in `perform'
 - app/services/find_expected_lap.rb:5:in `perform'
 - app/services/rowify_raw_times.rb:48:in `expected_lap'
 - app/services/rowify_raw_times.rb:42:in `block in add_lap_to_raw_times'
 - app/services/rowify_raw_times.rb:34:in `each'
 - app/services/rowify_raw_times.rb:34:in `add_lap_to_raw_times'
 - app/services/rowify_raw_times.rb:22:in `build'
 - app/services/rowify_raw_times.rb:8:in `build'
 - app/controllers/api/v1/event_groups_controller.rb:82:in `pull_raw_times'
 - config/initializers/wrap_parameters.rb:17:in `process_action'

**Comment by moveson** [comment]
Fixed.
