### ISSUE TITLE
session[:return_to] redirects not working properly

### ISSUE THREAD

**Issue by moveson** [SplitTime/OpenSplitTime#2]
Certain views may be accessed from different referral sources. For example, split/edit may be accesed from the splits/index view or from the course/show view. For a seamless user experience, the pages should redirect properly to the referring page. 

I have attempted to implement a technique that sets session[:return_to] = request.referer in the edit action and then uses session.delete(:return_to) in the update action, as recommended in the first answer in [this discussion](http://stackoverflow.com/questions/2139996). But results are inconsistent. See the splits_controller and locations_controller for examples.

I have tried a different technique in the split#destroy action with better luck. But this technique seems more fragile, and I would much prefer a proper solution.

@davetwofeetonthedirt, could you take a look at this issue?

**Comment by randalloveson** [comment]
Attached.
