### ISSUE TITLE
Importer tests do not pass

### ISSUE THREAD

**Issue by moveson** [SplitTime/OpenSplitTime#39]
The tests located in `spec/models/importer_spec.rb` do not pass. The problem seems to be in the creation of `@importer`, which should be an instance of `SplitImporter`. One of the parameters for `SplitImporter` is a file, and I have not been able to get it working. The file is currently located in `spec/fixtures/files`, which is the correct place based on my research, but it does not work.

If it's possible to use a real file as a parameter in rspec, this should be fixed. If not, then perhaps the code should be changed so we can stub it out instead of importing a real file?

**Comment by davetwofeetonthedirt** [comment]
I'll have a look.

**Comment by moveson** [comment]
Thanks for your help, Dave!
