### ISSUE TITLE
Fuzzy matching of runner's names isn't working that well

### ISSUE THREAD

**Issue by billwright** [SplitTime/OpenSplitTime#407]
When I search for "Synder" I don't see any Synder's at all on the first page of results. It is matching Synder, but on later pages. My idea is to show the exact matches at the top of the search list and then have some sort of break before listing all the others in alphabetical order.

Also, when I search for "Zach Roth" it is not finding "Zachary Roth". I would expect this to match.

**Comment by moveson** [comment]
The first problem appears to be caused by an automatic sort parameter that is injected, destroying rank priority. 

The second problem is different. I'm not sure we can keep the dmetaphone fuzzy matching working at the same time that we do a string subset search, but I'll look into that.

**Comment by moveson** [comment]
There seems to be no good way to use fuzzy matching without it dominating the ranking, so I've removed dmetaphone for now.

I also enabled prefix searching, so `Zach` will now match `Zachary`.

**Comment by moveson** [comment]
The problem was that, even without reordering the search results, the code was busting up the search result and parsing it using result ids. This can be solved using a full database search solution.

**Comment by moveson** [comment]
Working much better now.
- Fuzzy matching works but is de-prioritized compared to exact matches
- Prefix matching works ("Zach" will find "Zachary")
- State and country searching has been preserved by adding a couple of searchable columns on the `people` and `efforts` tables
