### ISSUE TITLE
Effort#show view needs a "Start effort" button

### ISSUE THREAD

**Issue by moveson** [SplitTime/OpenSplitTime#41]
The Event#stage (admin) view contains a "Start all efforts" button that is visible when the associated event has not yet started (`event.started? == false`). This is used when efforts have been entered or imported but no times have yet been entered. The events_controller#start_all_efforts action creates a new starting split_time for each effort in the event.

There is currently no way to start an individual effort from the effort view page. That page needs a "Start effort" button that will create a starting split_time for the associated effort. 

Access policy should parallel the access policy for starting all efforts, that is to say, the action should be available (and button should be visible) only if the current user is an admin, is the creator of the event, or is a steward of the race.

**Comment by moveson** [comment]
@nplasterer Would you be willing to take this issue on? It will be a good introduction to the event/effort/split_time side of the schema.

**Comment by nplasterer** [comment]
@moveson for sure I can pick this up. Might be a few days till I can get around to starting this.

**Comment by moveson** [comment]
Thank you!

**Comment by moveson** [comment]
@nplasterer Have you had a chance to look at this yet? I'm happy to walk you through the schema if that would be helpful.

**Comment by nplasterer** [comment]
Sorry @moveson been very busy with work and taking some vacation away from my laptop around the holidays. I'll ping you if I have any questions when I get started.

**Comment by moveson** [comment]
Sounds great.

**Comment by moveson** [comment]
Starting a single effort is now handled via the Live Entry screen, so this issue is obsolete.
