### ISSUE TITLE
Minor get_live_effort_data Server Error

### ISSUE THREAD

**Issue by legoabram** [SplitTime/OpenSplitTime#47]
I encountered a minor error while submitting data to get_live_effort_data. It may be a frontend problem, but we should double check.

http://localhost:3000/live/events/3/get_live_effort_data?splitId=2&bibNumber=12&timeIn=22%3A06%3A35&timeOut=22%3A06%3A35

![screenshot from 2017-01-05 22-31-22](https://cloud.githubusercontent.com/assets/4633731/21708510/b69b8de6-d396-11e6-8e26-21bd9200a1fe.png)

**Comment by moveson** [comment]
Added nil handling in DataStatus#determine, which fixes this problem. Please pull from master and let me know if this is resolved.
