### ISSUE TITLE
Lottery | Draw Tickets sometimes doesn't work

### ISSUE THREAD

**Issue by tbstockton** [SplitTime/OpenSplitTime#590]
Clicking the Draw Tickets button doesn't appear to update the Progress bar after leaving "Draw Tickets" by clicking on the "Setup" tab and then returning to "Draw Tickets" to draw more tickets. Inconsistent hard to reproduce behavior, almost appears to be long delay. 

Doesn't throw an error in the console.

**Comment by moveson** [comment]
I was having some similar difficulties this morning (Monday, October 11). For me, the trouble was that one of the test lotteries had more slots than it had entrants to draw, so the "Draw Ticket" button remained enabled even though there was nobody left to draw.

@tbstockton Is it possible this was what you were experiencing?

**Comment by moveson** [comment]
Further research shows that this can occur when switching back and forth from Setup to Draw Tickets even when it's not done very quickly. And once it's a problem, it seems to remain a problem and sometimes gets worse the more switching is done.

A page refresh seems to fix the problem every time. I'm going to try disabling the Turbo Drive feature when switching between these two pages. That will make for slightly less snappy feel when switching, but it may solve this problem.

**Comment by moveson** [comment]
#595 appears to have fixed the problem. 

@tbstockton Please let me know if you are able to reproduce the problem with this fix in place.
