### ISSUE TITLE
Google analytics throws errors in console

### ISSUE THREAD

**Issue by tbstockton** [SplitTime/OpenSplitTime#591]
Clicking on the "Draw Ticket" throws an error in the console:

<img width="877" alt="Screen Shot 2021-10-11 at 6 23 35 PM" src="https://user-images.githubusercontent.com/28879991/136870386-f68d97a0-70a6-43af-999a-47bceaed78b6.png">

**Comment by moveson** [comment]
Thanks for catching this. 

I am seeing this error on every page load throughout the app. It does not appear to be directly related to the lottery. On first review it appears to be related to the Google analytics code.

**Comment by moveson** [comment]
Fixed!
