### ISSUE TITLE
Import Jobs | Choose File doesn't open dialog

### ISSUE THREAD

**Issue by tbstockton** [SplitTime/OpenSplitTime#637]
On the Import Entrants page the Choose File field doesn't respond at all on clicking the button. No errors are thrown in the console.

<img width="496" alt="Screen Shot 2021-11-28 at 6 43 36 PM" src="https://user-images.githubusercontent.com/28879991/143796625-26044aae-ba2e-4489-be3d-61b1d060121e.png">

**Comment by tbstockton** [comment]
Drag and drop seems to have tried to work but looks like the file size is exceeded .
<img width="497" alt="Screen Shot 2021-11-28 at 6 51 49 PM" src="https://user-images.githubusercontent.com/28879991/143796894-b7c5403a-bf01-42d2-a166-5dabf5d36bc5.png">
.

**Comment by tbstockton** [comment]
Turns there were too many entrants in the file (all entrants that have entered in the history of the run rather than just 2022 entrants). I trimmed out the extra  and now I get ...

<img width="497" alt="Screen Shot 2021-11-28 at 7 08 28 PM" src="https://user-images.githubusercontent.com/28879991/143798078-859ad36e-cb73-43df-9a58-161fc7236def.png">

**Comment by moveson** [comment]
This is the same as #623. The fix is now in production and should fix this bug.

**Comment by moveson** [comment]
We have another problem, documented in #640. But the problem described in this issue has been fixed.
